name: Build DLL (Size Optimized)

on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-windows-dll:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Configure CMake (DLL, size optimized)
        run: >
          cmake -S . -B build `
            -G Ninja `
            -DCMAKE_BUILD_TYPE=Release `
            -DBUILD_SHARED_LIBS=ON `
            -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON

      - name: Build
        run: cmake --build build --config Release

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: libheif-dll
          path: |
            build/**/*.dll
